[build]
  command = "npx astro build"
  publish = "dist"

[functions]
  # Directory for Netlify functions (empty since we're using Supabase)
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200